openapi: 3.0.2
info:
  title: AI Tool Search API
  description: An API for searching AI tools based on query and payment model.
  version: 1.0.0
servers:
  - url: https://api.aishowcase.io
paths:
  /api/search:
    get:
      summary: Search
      description: Accepts a search query and an optional payment model filter.
      operationId: search_get
      parameters:
        - name: q
          in: query
          description: Search query
          required: true
          schema:
            type: string
        - name: p
          in: query
          description: Payment model filter (optional)
          required: false
          schema:
            type: string
            enum: [free, paid, open_source]
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResponse"
components:
  schemas:
    SearchResponse:
      title: SearchResponse
      required:
        - success
        - message
        - data
      type: object
      properties:
        success:
          type: boolean
        message:
          type: integer
        data:
          type: array
          items:
            $ref: "#/components/schemas/ToolData"
    ToolData:
      title: ToolData
      required:
        - name
        - url
        - excerpt
        - payment_model
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        excerpt:
          type: string
        payment_type:
          $ref: string