
openapi: 3.0.1
info:
  title: BART Real-Time
  description: Allows the user to get real-time BART information for a specified origination station and direction.
  version: 'v1'
servers:
  - url: https://bart-plugin.onrender.com
paths:
  /bart/realtime:
    get:
      operationId: getBartRealTime
      summary: Get real-time BART information
      parameters:
        - name: origination_station
          in: query
          description: The abbreviation for the origination station (e.g., '12th' for 12th Street Station).
          required: true
          schema:
            type: string
        - name: direction
          in: query
          description: The direction of travel ('n' for northbound, 's' for southbound).
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    description: The JSON response from the BART real-time API containing real-time BART information.
