openapi: 3.0.1
info:
  title: Keyplays Football/Soccer Plugin
  description: A plugin that provides detailed football match information.
  version: 'v1'
servers:
  - url: https://keyplays.malcsilberman.repl.co
paths:
  /chat/fetch_game:
    get:
      operationId: fetch_game
      summary: Fetch game data for dates for a team or league, returns participants, tvstations, weather, venue, referees. Can request commentary, lineups, statistics, events, sidelined players, predictions.
      parameters:
        - name: team_search
          in: query
          description: The team name or part of the team name to search for
          required: false
          schema:
            type: string
        - name: country_league
          in: query
          description: The country or league name to search for
          required: false
          schema:
            type: string
        - name: iso
          in: query
          description: The ISO 3166-2 code to filter the results by country
          required: false
          schema:
            type: string
        - name: start_date
          in: query
          description: The start date for the date range to search for games (format YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: The optional end date for the date range to search for games (format YYYY-MM-DD) uses the start date if not present
          required: false
          schema:
            type: string
            format: date
        - name: timezone
          in: query
          description: Overrides the timezone if the user provides an optional timezone
          required: false
          schema:
            type: string
        - name: include
          in: query
          description: Additional data to be requested in the response; possible values are trends, timeline, commentary, lineups, statistics, events, sidelined, predictions
          required: false
          schema:
            type: string
            enum:
              - trends
              - timeline
              - commentary
              - lineups
              - statistics
              - events
              - sidelined
              - predictions
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the response properties here
  /chat/fetch_standings:
    get:
      operationId: fetchStandings
      summary: Get football standings tables try return all teams in table format
      parameters:
        - name: league_search
          in: query
          description: name of the league and if possible prefix the country since some leagues share the same names, it is also possible to search for a countries league and get back the league
          required: false
          schema:
            type: string
        - name: timezone
          in: query
          description: Overides the timezone if the use provides and optional timezone
          required: false
          schema:
            type: string
        - in: query
          name: year
          schema:
            type: string
          description: The year for the standings, in cases where season cross years we use the start year, if a user gives 2020/2021 then use 2020            
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the response properties here
  /chat/fetch_tvstations:
    get:
      operationId: fetchTvStations
      summary: Get TV stations broadcasting football matches, specify in order an optional country and leaque name, or blank for all leagues, return data should include team postions.
      parameters:
        - name: league_search
          in: query
          description: Name of country or league or mix of these two returns a league id.
          required: false
          schema:
            type: string
        - name: iso
          in: query
          description: The optional ISO 3166-2 code to filter the results by country.
          required: false
          schema:
            type: string
        - name: date
          in: query
          description: The date for which to retrieve match information (format YYYY-MM-DD). If not provided, todays date will be used.
          required: false
          schema:
            type: string
            format: date
        - name: timezone
          in: query
          description: Overides the timezone if the user provides an optional timezone.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Returns league name, date, games, teams playing, team positions, tv stations for your country.
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the response properties here
  /chat/leagues_today:
    get:
      operationId: fetchLeaguesToday
      summary: Fetches worldwide leagues and games being played today or provide a date, return leagues and games.
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date
          description: Date for which to fetch leagues and games
        - in: query
          name: iso
          schema:
            type: string
          description: ISO 3166-2 country code
        - in: header
          name: openai-subdivision-1-iso-code
          schema:
            type: string
          required: false
          description: OpenAI subdivision ISO code
        - in: query
          name: timezone
          schema:
            type: string
          description: Timezone      
      responses:
        "200":
          description: Returns league name, games, teams playing, starting date/time, result
          content:
            application/json:
              schema:
                type: object
                properties:
  /chat/playerSearch:
    get:
      operationId: fetchPlayerSearch
      summary: Fetches details for a player using search by providing the player name. Can request statistics as an include.
      parameters:
        - in: query
          name: name
          schema:
            type: string
          description: Name of the player for which to fetch details must be spelled correctly
        - in: query
          name: iso
          schema:
            type: string
          description: ISO 3166-2 country code
        - in: header
          name: openai-subdivision-1-iso-code
          schema:
            type: string
          required: false
          description: OpenAI subdivision ISO code
        - in: query
          name: timezone
          schema:
            type: string
          description: Timezone
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
        - in: query
          name: year
          schema:
            type: string
          description: The year for the statistics, if seasons cross years then input 2022 will give statistics for 2021/2022 and 2022/2023 seasons            
        - name: include
          in: query
          description: Additional data to be requested in the response; possible value is statistics
          required: false
          schema:
            type: string
            enum:
              - statistics          
      responses:
        "200":
          description: Returns player details such as country, city, nationality, transfers, teams, trophies, seasons, statistics etc.
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties here
  /chat/teamSquad:
    get:
      operationId: fetchTeamSquad
      summary: Fetches squad, players and coaches details for a particular team.
      parameters:
        - in: query
          name: team_search
          schema:
            type: string
          description: Name of the team for which to fetch squad, players and coaches details
        - in: query
          name: iso
          schema:
            type: string
          description: ISO 3166-2 country code
        - in: header
          name: openai-subdivision-1-iso-code
          schema:
            type: string
          required: false
          description: OpenAI subdivision ISO code
        - in: query
          name: timezone
          schema:
            type: string
          description: Timezone
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
      responses:
        "200":
          description: Returns players and coaches details for a particular team, including country, nationality, detailed position, coaches and coaches country.
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties here
        "400":
          description: Returns an error message if the team name is not provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /chat/fetchUpcomingTeams:
    get:
      operationId: fetchUpcomingTeams
      summary: Fetches upcoming information for a particular team.
      parameters:
        - in: query
          name: team_search
          schema:
            type: string
          description: Name of the team for which to fetch upcoming information
        - in: query
          name: iso
          schema:
            type: string
          description: ISO 3166-2 country code
        - in: header
          name: openai-subdivision-1-iso-code
          schema:
            type: string
          required: false
          description: OpenAI subdivision ISO code
        - in: query
          name: timezone
          schema:
            type: string
          description: Timezone
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number for pagination
      responses:
        "200":
          description: Returns upcoming information for a particular team, including venue, sidelined players, coaches, referees, league details, scores, start times, player images.
          content:
            application/json:
              schema:
                type: object
                properties:
                  # Define the properties here
        "400":
          description: Returns an error message if the team name is not provided.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    