openapi: 3.0.1
info:
  title: ScholarAI-test
  description: Allows the user to search facts and findings from scientific articles
  version: 'v1'
servers:
  - url: https://scholar-ai.net
paths:
  /api/abstracts:
    get:
      operationId: searchAbstracts
      summary: Get relevant paper abstracts by keywords search
      parameters:
        - name: keywords
          in: query
          description: Keywords of inquiry which should appear in article
          required: true
          schema:
            type: string
        - name: sort
          in: query
          description: The sort order for results, defaults to cited_by_count. Valid values are cited_by_count or publication_date.
          required: false
          schema:
            type: string
        - name: query
          in: query
          description: The user query
          required: true
          schema:
            type: string
        - name: peer_reviewed_only
          in: query
          description: Whether to only return peer reviewed articles. Defaults to true, ChatGPT should cautiously suggest this value can be set to false
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/searchAbstractsResponse'
  /api/fulltext:
    get:
      operationId: getFullText
      summary: Get full text of a paper by URL for PDF
      parameters:
        - name: pdf_url
          in: query
          description: URL for PDF
          required: true
          schema:
            type: string
        - name: chunk
          in: query
          description: chunk number to retrieve, defaults to 1
          required: false
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getFullTextResponse'
components:
  schemas:
    searchAbstractsResponse:
      type: object
      properties:
        abstracts:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              abstract:
                type: string
                description: Summary of the context, methods, results, and conclusions of the paper.
              doi:
                type: string
                description: The DOI of the paper.
              landing_page_url:
                type: string
                description: Link to the paper on its open-access host.
              pdf_url:
                type: string
                description: Link to the paper PDF.
              publicationDate:
                type: string
                description: The date the paper was published in YYYY-MM-DD format.
              relevance:
                type: number
                description: The relevance of the paper to the search query. 1 is the most relevant.
              creators:
                type: array
                items:
                  type: string
                  description: The name of the creator.
              cited_by_count:
                type: number
                description: The number of citations of the article.

          description: The list of relevant abstracts.
    getFullTextResponse:
      type: object
      properties:
        full_text:
          type: string
          description: The full text of the paper.
        pdf_url:
          type: string
          description: The PDF URL of the paper.
        chunk:
          type: number
          description: The chunk of the paper.
        total_chunk_num:
          type: number
          description: The total chunks of the paper.