openapi: 3.0.1
info:
  title: Prompt Perfect
  description: A plugin that rephrases prompts deemed unclear, overly brief, or missing necessary information into clearer, more specific, and contextual prompts.
  version: 'v1'
servers:
  - url: https://xyz-prompt-perfect.uc.r.appspot.com
paths:
  /rephrase:
    post:
      operationId: rephrasePrompt
      summary: Rephrase the given prompt
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Prompt'
            example:
              text: "Write a tweet"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RephrasedPrompt'
              example:
                text: "Compose a highly detailed and engaging tweet. Keep the tweet within the 280-character limit"
components:
  schemas:
    Prompt:
      type: object
      properties:
        conversation_id:
          type: string
          description: The conversation ID.
        text:
          type: string
          description: The prompt text to be rephrased.
    RephrasedPrompt:
      type: object
      properties:
        conversation_id:
          type: string
          description: The conversation ID.
        rephrased:
          type: object
          properties:
            text:
              type: string
              description: The rephrased prompt text.